power<-read.table("household_power_consumption.txt",sep=";",stringsAsFactors=FALSE,skip=66637,nrows=2880,col.names=c("Date","Time","GAP","GRP","Voltage","GI","SM1","SM2","SM3"))
x<-paste(power$Date,power$Time)
x<-strptime(x,format="%d/%m/%Y %H:%M:%S")
power<-cbind(x,power)
png(filename="plot4.png",
    width=480,height=480)
par(mfrow=c(2,2))
plot(power$x,power$GAP,ylab="Global Active Power",type="l",xlab="")
plot(power$x,power$Voltage,xlab="date/time",ylab="Voltage",type="l")
plot(power$x,power$SM1,type="l",ylab="Energy sub metering",xlab="")
lines(power$x,power$SM2,col="red")
lines(power$x,power$SM3,col="blue")
legend("topright",col=c("black","red","blue"),lwd=2,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
plot(power$x,power$GRP,type="l",ylab="Global_reactive_power",xlab="date/time",lwd=1)
dev.off()